<a href="https://colab.research.google.com/github/Bady9898/Decision-Tree-Random-Forest/blob/main/Fraud-Check_Decision-Tree_Random-Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import  DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report

In [2]:
#import csv file
fraud = pd.read_csv("Fraud_check.csv")

In [3]:
fraud

Undergrad Marital.Status  Taxable.Income  City.Population  \
0          NO         Single           68833            50047   
1         YES       Divorced           33700           134075   
2          NO        Married           36925           160205   
3         YES         Single           50190           193264   
4          NO        Married           81002            27533   
..        ...            ...             ...              ...   
595       YES       Divorced           76340            39492   
596       YES       Divorced           69967            55369   
597        NO       Divorced           47334           154058   
598       YES        Married           98592           180083   
599        NO       Divorced           96519           158137   

     Work.Experience Urban  
0                 10   YES  
1                 18   YES  
2                 30   YES  
3                 15   YES  
4                 28    NO  
..               ...   ...  
595                7   YES  
596                2   YES  
597                0   YES  
598               17    NO  
599               16    NO  

[600 rows x 6 columns]

In [4]:
fraud.describe()

Taxable.Income  City.Population  Work.Experience
count      600.000000       600.000000       600.000000
mean     55208.375000    108747.368333        15.558333
std      26204.827597     49850.075134         8.842147
min      10003.000000     25779.000000         0.000000
25%      32871.500000     66966.750000         8.000000
50%      55074.500000    106493.500000        15.000000
75%      78611.750000    150114.250000        24.000000
max      99619.000000    199778.000000        30.000000

In [5]:
fraud.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Undergrad        600 non-null    object
 1   Marital.Status   600 non-null    object
 2   Taxable.Income   600 non-null    int64 
 3   City.Population  600 non-null    int64 
 4   Work.Experience  600 non-null    int64 
 5   Urban            600 non-null    object
dtypes: int64(3), object(3)
memory usage: 28.2+ KB


In [7]:
fraud = fraud.rename(columns={'Undergrad':'Under_Graduate','Marital.Status':'Martial', 'Taxable.Income': 'Taxable_inc','City.Population': 'Population' , 'Work.Experience' : 'Work_Exp'})

In [8]:
fraud

Under_Graduate   Martial  Taxable_inc  Population  Work_Exp Urban
0               NO    Single        68833       50047        10   YES
1              YES  Divorced        33700      134075        18   YES
2               NO   Married        36925      160205        30   YES
3              YES    Single        50190      193264        15   YES
4               NO   Married        81002       27533        28    NO
..             ...       ...          ...         ...       ...   ...
595            YES  Divorced        76340       39492         7   YES
596            YES  Divorced        69967       55369         2   YES
597             NO  Divorced        47334      154058         0   YES
598            YES   Married        98592      180083        17    NO
599             NO  Divorced        96519      158137        16    NO

[600 rows x 6 columns]

In [10]:
fraud["Under_Graduate"].value_counts()

YES    312
NO     288
Name: Under_Graduate, dtype: int64

In [11]:
fraud["Martial"].value_counts()

Single      217
Married     194
Divorced    189
Name: Martial, dtype: int64

In [12]:
fraud["Urban"].value_counts()

YES    302
NO     298
Name: Urban, dtype: int64

Assume: taxable_income <= 30000 as “Risky=0” and others are “Good=1”

In [15]:
fraud["income"]="<=30000"
fraud.loc[fraud["Taxable_inc"]>=30000,"income"]="Good"
fraud.loc[fraud["Taxable_inc"]<=30000,"income"]="Risky"

In [16]:
fraud["income"].unique()

array(['Good', 'Risky'], dtype=object)

In [17]:
fraud["income"].value_counts()

Good     476
Risky    124
Name: income, dtype: int64

In [18]:
### dropping the Taxable.Income columns
fraud = fraud.drop(['Taxable_inc'],axis=1)

In [19]:
fraud.isnull().sum()

Under_Graduate    0
Martial           0
Population        0
Work_Exp          0
Urban             0
income            0
dtype: int64

In [21]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
for column_name in fraud.columns:
    if fraud[column_name].dtype == object:
        fraud[column_name] = le.fit_transform(fraud[column_name])
    else:
        pass

In [22]:
features = fraud.iloc[:,0:5]
labels = pd.DataFrame(fraud.iloc[:,5])

In [23]:
features

Under_Graduate  Martial  Population  Work_Exp  Urban
0                 0        2       50047        10      1
1                 1        0      134075        18      1
2                 0        1      160205        30      1
3                 1        2      193264        15      1
4                 0        1       27533        28      0
..              ...      ...         ...       ...    ...
595               1        0       39492         7      1
596               1        0       55369         2      1
597               0        0      154058         0      1
598               1        1      180083        17      0
599               0        0      158137        16      0

[600 rows x 5 columns]

In [24]:
labels

income
0         0
1         0
2         0
3         0
4         0
..      ...
595       0
596       0
597       0
598       0
599       0

[600 rows x 1 columns]

In [25]:
fraud["income"].value_counts()

0    476
1    124
Name: income, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features,labels, test_size=0.3, stratify=labels)

In [27]:
print(y_train["income"].value_counts())
print(y_test["income"].value_counts())

0    333
1     87
Name: income, dtype: int64
0    143
1     37
Name: income, dtype: int64


In [28]:
##Converting the column names into the list format
colnames = list(fraud.columns)
predictors = colnames[:5]
target = colnames[5]


In [29]:
colnames

['Under_Graduate', 'Martial', 'Population', 'Work_Exp', 'Urban', 'income']

In [30]:
predictors

['Under_Graduate', 'Martial', 'Population', 'Work_Exp', 'Urban']

In [31]:
target

'income'

In [32]:
fraud.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Under_Graduate  600 non-null    int64
 1   Martial         600 non-null    int64
 2   Population      600 non-null    int64
 3   Work_Exp        600 non-null    int64
 4   Urban           600 non-null    int64
 5   income          600 non-null    int64
dtypes: int64(6)
memory usage: 28.2 KB


# Prediction using Decision Tree Classifier

In [33]:
from sklearn.tree import DecisionTreeClassifier as DT

model = DT(criterion = 'entropy')
model.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [34]:
from sklearn.metrics import accuracy_score


In [35]:
##Prediciton on train data 
pred_train = pd.DataFrame(model.predict(x_train))
pred_train

0
0    0
1    0
2    0
3    0
4    0
..  ..
415  1
416  0
417  1
418  1
419  0

[420 rows x 1 columns]

In [36]:
### Finding the accuracy of train data
acc_train = accuracy_score(y_train,pred_train)
acc_train

1.0

In [37]:
##Confusion matrix for train data
from sklearn.metrics import confusion_matrix

In [38]:
cm = pd.DataFrame(confusion_matrix(y_train,pred_train))

In [39]:
cm

0   1
0  333   0
1    0  87

In [40]:
##Prediction on test data
pred_test = pd.DataFrame(model.predict(x_test))
pred_test

0
0    1
1    0
2    0
3    0
4    0
..  ..
175  0
176  0
177  0
178  0
179  1

[180 rows x 1 columns]

In [41]:
acc_test = accuracy_score(y_test,pred_test)
acc_test

0.6111111111111112

In [42]:
#confusion matrix for test data
cm_test = confusion_matrix(y_test,pred_test)
cm_test

array([[103,  40],
       [ 30,   7]])

# Prediction Using Random Forest Classifier

In [43]:
##Model building
from sklearn.ensemble import RandomForestClassifier as RF
model = RF(n_jobs = 3,n_estimators = 15, oob_score = True, criterion = "entropy")
model.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier(criterion='entropy', n_estimators=15, n_jobs=3,
                       oob_score=True)

In [44]:
model.estimators_
model.classes_
model.n_features_
model.n_classes_

model.n_outputs_

model.oob_score_

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:103: FutureWarning: Attribute `n_features_` was deprecated in version 1.0 and will be removed in 1.2. Use `n_features_in_` instead.
  warnings.warn(msg, category=FutureWarning)


0.7357142857142858

In [45]:
##Predictions on train data
prediction = model.predict(x_train)
prediction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

In [46]:
##Accuracy
# For accuracy 
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_train,prediction)
accuracy

0.9857142857142858

In [47]:
##Confusion matrix
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_train,prediction)
confusion

array([[333,   0],
       [  6,  81]])

In [48]:
##Prediction on test data
pred_test = model.predict(x_test)
pred_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [49]:
##Accuracy
acc_test =accuracy_score(y_test,pred_test)
acc_test

0.7444444444444445